In [23]:
# Library yang digunakan
import pandas as pd
import re

## 💡 Load Data

In [ ]:
#Load Dataser
version = '5.4'
file_path = f"../data/review_genshin_{version}.csv"
df = pd.read_csv(file_path)

In [25]:
# Show Dataset
df.head(10)

,ReviewID,Username,UserImage,Content,Score,ThumbsUpCount,ReviewCreatedVersion,at,ReplyContent,RepliedAt,AppVersion
0,873f5b86-5b5c-46fd-b63a-68ce04b88eed,muhammad hafiz Baihaqi,https://play-lh.googleusercontent.com/a/ACg8oc...,sangat menikmati story quest nya,5,0,5.4.0_30057195_30231699,2025-03-24 23:50:10,NaN,NaN,5.4.0_30057195_30231699
1,fcae916f-4999-43b2-bf2f-03787cb2242e,hamzahjr 1111,https://play-lh.googleusercontent.com/a-/ALV-U...,"seruuuu.. udh cocok ama ni game drpd ww, tpi u...",4,0,5.4.0_30057195_30231699,2025-03-24 23:47:34,NaN,NaN,5.4.0_30057195_30231699
2,b91228ca-5049-49f2-afe6-e40be87c9b65,Rehan Kun?,https://play-lh.googleusercontent.com/a-/ALV-U...,Untuk Saat Ini Bagus Lah Gw kasih Lima⭐🤭😹,5,1,5.4.0_30057195_30231699,2025-03-24 23:40:09,NaN,NaN,5.4.0_30057195_30231699
3,2739b656-641d-4709-ab23-7a8e821ddeaa,Silva harnawi Raisa,https://play-lh.googleusercontent.com/a-/ALV-U...,"Sebenarnya game nya sudah bagus, grafik yang m...",1,391,5.3.0_29183395_29332470,2025-03-24 23:06:12,NaN,NaN,5.3.0_29183395_29332470
4,18a28284-8ca6-4fa4-a26b-1a36b346eb88,Dodol Jeli,https://play-lh.googleusercontent.com/a-/ALV-U...,Supri mujidin agus dan sugi kurang menyukai ge...,2,2,4.3.0_19705728_19706476,2025-03-24 22:50:52,NaN,NaN,4.3.0_19705728_19706476
5,fcec75fb-6be6-448f-949f-59f08f3fea97,MIRAI Voin,https://play-lh.googleusercontent.com/a-/ALV-U...,semoga hari ku win rate off terus,5,0,NaN,2025-03-24 22:31:46,NaN,NaN,NaN
6,c86e248c-acbb-4987-98a4-89c0cf67cd84,Ayuk Curup,https://play-lh.googleusercontent.com/a/ACg8oc...,game nya bagus banget game yang paling ku suka...,4,0,5.4.0_30057195_30231699,2025-03-24 22:24:43,NaN,NaN,5.4.0_30057195_30231699
7,27f7b0bc-ad91-421c-8cd1-c4ec6e990138,Rahmad Dogiel,https://play-lh.googleusercontent.com/a/ACg8oc...,gamenya sangat seru cuman akan lebih seru lagi...,5,0,5.4.0_30057195_30231699,2025-03-24 22:10:29,NaN,NaN,5.4.0_30057195_30231699
8,318bf1dc-4fdd-42ac-9848-67ee2697aae8,Muhamad Jafar sodiq,https://play-lh.googleusercontent.com/a/ACg8oc...,Nice,5,0,5.4.0_30057195_30231699,2025-03-24 21:54:22,NaN,NaN,5.4.0_30057195_30231699
9,263509bf-4092-4091-9ce9-b2dda4046ade,Muhamad Faris Al-akbar,https://play-lh.googleusercontent.com/a-/ALV-U...,absolute cinema,5,0,5.4.0_30057195_30231699,2025-03-24 21:45:47,NaN,NaN,5.4.0_30057195_30231699

| Kolom                | Deskripsi                                 |
|----------------------|--------------------------------------------|
| `ReviewId`           | ID unik untuk review                       |
| `UserName`           | Nama pengguna                              |
| `UserImage`          | URL foto profil pengguna                   |
| `Content`            | Isi review                                 |
| `Score`              | Nilai rating (1–5)                         |
| `ThumbsUpCount`      | Jumlah likes pada review                   |
| `ReviewCreatedVersion` | Versi aplikasi saat review dibuat        |
| `at`                 | Tanggal review                             |
| `ReplyContent`       | Balasan dari developer (jika ada)          |
| `RepliedAt`          | Tanggal balasan                            |
| `AppVersion`         | Versi aplikasi                             |

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2144 entries, 0 to 2143
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ReviewID              2144 non-null   object
 1   Username              2144 non-null   object
 2   UserImage             2144 non-null   object
 3   Content               2144 non-null   object
 4   Score                 2144 non-null   int64
 5   ThumbsUpCount         2144 non-null   int64
 6   ReviewCreatedVersion  1358 non-null   object
 7   at                    2144 non-null   object
 8   ReplyContent          337 non-null    object
 9   RepliedAt             337 non-null    object
 10  AppVersion            1358 non-null   object
dtypes: int64(2), object(9)
memory usage: 184.4+ KB

## 🗃️ Drop Kolom

In [ ]:
df_wrangling = df.drop(
    columns=['Username', 'UserImage', 'ReplyContent', 'RepliedAt', 'ReviewCreatedVersion'])

Kolom 'userName' dan 'userImage' di-drop karena tidak mengandung informasi tekstual yang relevan untuk analisis NLP — mereka hanya metadata pengguna.  
Kolom 'replyContent' dan 'repliedAt' juga tidak digunakan karena fokus analisis NLP berada pada konten utama, bukan pada balasan atau timestamp-nya.
Kolom 'ReviewCreatedVersion' juga di-drop karena informasinya redundan — nilainya sama dengan kolom 'appVersion'.

## 🔄 Ubah Tipe Data

In [ ]:
df_wrangling['at'] = pd.to_datetime(df_wrangling['at'], errors='coerce')

## 🔄 Transform Nilai Data

In [ ]:
def version_simplyfied(v):
    if pd.isna(v):
        return version
    match = re.match(r"^([0-9]+)\.([0-9]+)", str(v))
    if match:
        return f"{match.group(1)}.{match.group(2)}"
    return version  # fallback jika tidak cocok juga


df_wrangling['AppVersion'] = df_wrangling['AppVersion'].apply(version_simplyfied)

## 🔍 Cek Outlier / Nilai Tidak Normal

In [ ]:
df_filtered = df_wrangling[df_wrangling['AppVersion'] == version]

In [31]:
df_filtered.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1917 entries, 0 to 2137
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ReviewID       1917 non-null   object
 1   Content        1917 non-null   object
 2   Score          1917 non-null   int64
 3   ThumbsUpCount  1917 non-null   int64
 4   at             1917 non-null   datetime64[ns]
 5   AppVersion     1917 non-null   object
dtypes: datetime64[ns](1), int64(2), object(3)
memory usage: 104.8+ KB

In [32]:
df_filtered.head()

,ReviewID,Content,Score,ThumbsUpCount,at,AppVersion
0,873f5b86-5b5c-46fd-b63a-68ce04b88eed,sangat menikmati story quest nya,5,0,2025-03-24 23:50:10,5.4
1,fcae916f-4999-43b2-bf2f-03787cb2242e,"seruuuu.. udh cocok ama ni game drpd ww, tpi u...",4,0,2025-03-24 23:47:34,5.4
2,b91228ca-5049-49f2-afe6-e40be87c9b65,Untuk Saat Ini Bagus Lah Gw kasih Lima⭐🤭😹,5,1,2025-03-24 23:40:09,5.4
5,fcec75fb-6be6-448f-949f-59f08f3fea97,semoga hari ku win rate off terus,5,0,2025-03-24 22:31:46,5.4
6,c86e248c-acbb-4987-98a4-89c0cf67cd84,game nya bagus banget game yang paling ku suka...,4,0,2025-03-24 22:24:43,5.4

## 🗃️ Save Cleaned Data

In [33]:
# Simpan ke CSV
output_path = f'../data/review_genshin_{version}_cleaned.csv'
df_filtered.to_csv(output_path, index=False, encoding='utf-8-sig')