In [34]:
# Library yang digunakan
import pandas as pd
import re

## 💡 Load Data

In [35]:
#Load Dataser
version = '5.3'
file_path = f"../data/review_genshin_{version}.csv"
df = pd.read_csv(file_path)

In [36]:
# Show Dataset
df.head(10)

,ReviewID,Username,UserImage,Content,Score,ThumbsUpCount,ReviewCreatedVersion,at,ReplyContent,RepliedAt,AppVersion
0,869d8e47-1649-4823-a630-dd9dea341421,Andewsadfrtgy,https://play-lh.googleusercontent.com/a-/ALV-U...,Good,5,0,5.3.0_29183395_29332470,2025-02-10 22:52:05,NaN,NaN,5.3.0_29183395_29332470
1,a885d7e9-e655-4583-9686-488fe34938ad,21_Rafael Berly Johan,https://play-lh.googleusercontent.com/a-/ALV-U...,Moga menang rate off,5,0,5.3.0_29183395_29332470,2025-02-10 22:21:59,NaN,NaN,5.3.0_29183395_29332470
2,59910aae-3174-4ab6-8b9f-eb7d6ded0ffb,Nova Corps,https://play-lh.googleusercontent.com/a-/ALV-U...,Udah ganti aja Jagan jadi game petualangan jad...,1,1,5.3.0_29183395_29332470,2025-02-10 22:05:06,Kami mohon maaf atas ketidaknyamanan yang Anda...,2025-02-25 17:56:09,5.3.0_29183395_29332470
3,bfdbc555-30e4-42eb-9047-594d2aac4e0f,Aldi Ardiansyah,https://play-lh.googleusercontent.com/a-/ALV-U...,Pay to win banget cuih!,1,2,5.0.0_26041933_26161852,2025-02-10 22:00:39,NaN,NaN,5.0.0_26041933_26161852
4,5800da6b-abcb-48f6-8a63-6564c452d03b,Kaysar Ramadan,https://play-lh.googleusercontent.com/a-/ALV-U...,"Menurutku sih bagus² aja game ini, game petual...",5,0,5.3.0_29183395_29332470,2025-02-10 20:54:30,NaN,NaN,5.3.0_29183395_29332470
5,63ca4e9b-0282-4e85-8f66-618a28c42628,David Galaxy,https://play-lh.googleusercontent.com/a/ACg8oc...,Terlalu besar,4,0,5.3.0_29183395_29332470,2025-02-10 19:13:14,NaN,NaN,5.3.0_29183395_29332470
6,8cc8b53a-1be8-4071-8bf9-c9ca47bdfe7f,Vin,https://play-lh.googleusercontent.com/a/ACg8oc...,good,5,0,5.3.0_29183395_29332470,2025-02-10 18:47:56,NaN,NaN,5.3.0_29183395_29332470
7,c2c126c1-b22c-4cf5-854a-d3148abcd9c4,ADLI RAMADHAN,https://play-lh.googleusercontent.com/a-/ALV-U...,Saya benci game ini karna kalah rate off di ba...,1,2,5.3.0_29183395_29332470,2025-02-10 18:14:05,NaN,NaN,5.3.0_29183395_29332470
8,f37248a9-4043-4711-b143-e8ecb44204ce,Lulu Pitri,https://play-lh.googleusercontent.com/a/ACg8oc...,jelek,1,1,5.3.0_29183395_29332470,2025-02-10 17:50:14,Kami mohon maaf atas ketidaknyamanan yang Anda...,2025-02-25 17:55:44,5.3.0_29183395_29332470
9,679cadaa-6195-4ed7-a4ec-3ecf2325a388,Parrl Parel,https://play-lh.googleusercontent.com/a/ACg8oc...,Game kikir,2,0,NaN,2025-02-10 17:40:43,NaN,NaN,NaN

| Kolom                | Deskripsi                                 |
|----------------------|--------------------------------------------|
| `ReviewId`           | ID unik untuk review                       |
| `UserName`           | Nama pengguna                              |
| `UserImage`          | URL foto profil pengguna                   |
| `Content`            | Isi review                                 |
| `Score`              | Nilai rating (1–5)                         |
| `ThumbsUpCount`      | Jumlah likes pada review                   |
| `ReviewCreatedVersion` | Versi aplikasi saat review dibuat        |
| `at`                 | Tanggal review                             |
| `ReplyContent`       | Balasan dari developer (jika ada)          |
| `RepliedAt`          | Tanggal balasan                            |
| `AppVersion`         | Versi aplikasi                             |

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2471 entries, 0 to 2470
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ReviewID              2471 non-null   object
 1   Username              2471 non-null   object
 2   UserImage             2471 non-null   object
 3   Content               2471 non-null   object
 4   Score                 2471 non-null   int64
 5   ThumbsUpCount         2471 non-null   int64
 6   ReviewCreatedVersion  1727 non-null   object
 7   at                    2471 non-null   object
 8   ReplyContent          698 non-null    object
 9   RepliedAt             698 non-null    object
 10  AppVersion            1727 non-null   object
dtypes: int64(2), object(9)
memory usage: 212.5+ KB

## 🗃️ Drop Kolom

In [38]:
df_wrangling = df.drop(
    columns=['Username', 'UserImage', 'ReplyContent', 'RepliedAt', 'ReviewCreatedVersion'])

Kolom 'userName' dan 'userImage' di-drop karena tidak mengandung informasi tekstual yang relevan untuk analisis NLP — mereka hanya metadata pengguna.  
Kolom 'replyContent' dan 'repliedAt' juga tidak digunakan karena fokus analisis NLP berada pada konten utama, bukan pada balasan atau timestamp-nya.
Kolom 'ReviewCreatedVersion' juga di-drop karena informasinya redundan — nilainya sama dengan kolom 'appVersion'.

## 🔄 Ubah Tipe Data

In [39]:
df_wrangling['at'] = pd.to_datetime(df_wrangling['at'], errors='coerce')

## 🔄 Transform Nilai Data

In [40]:
def version_simplyfied(v):
    if pd.isna(v):
        return version
    match = re.match(r"^([0-9]+)\.([0-9]+)", str(v))
    if match:
        return f"{match.group(1)}.{match.group(2)}"
    return version  # fallback jika tidak cocok juga


df_wrangling['AppVersion'] = df_wrangling['AppVersion'].apply(version_simplyfied)

## 🔍 Cek Outlier / Nilai Tidak Normal

In [41]:
df_filtered = df_wrangling[df_wrangling['AppVersion'] == version]

In [42]:
df_filtered.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2032 entries, 0 to 2470
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ReviewID       2032 non-null   object
 1   Content        2032 non-null   object
 2   Score          2032 non-null   int64
 3   ThumbsUpCount  2032 non-null   int64
 4   at             2032 non-null   datetime64[ns]
 5   AppVersion     2032 non-null   object
dtypes: datetime64[ns](1), int64(2), object(3)
memory usage: 111.1+ KB

In [43]:
df_filtered.head()

,ReviewID,Content,Score,ThumbsUpCount,at,AppVersion
0,869d8e47-1649-4823-a630-dd9dea341421,Good,5,0,2025-02-10 22:52:05,5.3
1,a885d7e9-e655-4583-9686-488fe34938ad,Moga menang rate off,5,0,2025-02-10 22:21:59,5.3
2,59910aae-3174-4ab6-8b9f-eb7d6ded0ffb,Udah ganti aja Jagan jadi game petualangan jad...,1,1,2025-02-10 22:05:06,5.3
4,5800da6b-abcb-48f6-8a63-6564c452d03b,"Menurutku sih bagus² aja game ini, game petual...",5,0,2025-02-10 20:54:30,5.3
5,63ca4e9b-0282-4e85-8f66-618a28c42628,Terlalu besar,4,0,2025-02-10 19:13:14,5.3

## 🗃️ Save Cleaned Data

In [44]:
# Simpan ke CSV
output_path = f'../data/review_genshin_{version}_cleaned.csv'
df_filtered.to_csv(output_path, index=False, encoding='utf-8-sig')