In [28]:
# Library yang digunakan
import pandas as pd

## 💡 Load Data

In [29]:
#Load Dataser
file_path = "../data/review_genshin_uncleaned.csv"
df = pd.read_csv(file_path)

C:\Users\mirur\AppData\Local\Temp\ipykernel_25876\2310862458.py:3: DtypeWarning: Columns (8,9) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

In [30]:
# Show Dataset
df.head(10)

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,044af800-8184-463d-915d-e9382c4cdde7,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,👌,5,0,5.5.0_31400259_31451966,2025-04-06 12:38:51,NaN,NaN,5.5.0_31400259_31451966
1,e8e32740-62b4-4755-ae8b-0d50c71d7e33,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,comeback menggunakan Infinix 50 hot pro plus d...,5,0,1.5.0_2574575_2578841,2025-04-06 12:29:10,NaN,NaN,1.5.0_2574575_2578841
2,39853dd9-f562-4b6b-8621-7fa14465cfd3,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"Game baik wkwk tapi jujur aza dari segi lore, ...",5,0,5.5.0_31400259_31451966,2025-04-06 12:14:41,NaN,NaN,5.5.0_31400259_31451966
3,380ae1d4-16f2-4db2-83bd-f14ba776f76f,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Testing di HP Helio g99 dan ternyata sangat la...,5,1,5.5.0_31400259_31451966,2025-04-06 11:48:46,NaN,NaN,5.5.0_31400259_31451966
4,3548cb24-2d7e-423f-98f3-f11586a27144,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Benerin sistem preupdate di ps4 kacau banget!,5,2,5.5.0_31400259_31451966,2025-04-06 11:35:44,NaN,NaN,5.5.0_31400259_31451966
5,6d772cec-7d3f-4080-9296-164afd052765,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"ayolah mang hoyo, susah banget kalo gacha arte...",5,0,5.5.0_31400259_31451966,2025-04-06 11:12:59,NaN,NaN,5.5.0_31400259_31451966
6,4101f5f9-bdb9-41e4-b540-2f952d146c30,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Grafiknya kurang hd padahal sudah disetingan t...,4,0,5.5.0_31400259_31451966,2025-04-06 11:12:41,NaN,NaN,5.5.0_31400259_31451966
7,5a67f5c8-1014-4cb9-9a16-618386cf43a9,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,keren anjayyy,5,0,5.5.0_31400259_31451966,2025-04-06 10:11:11,NaN,NaN,5.5.0_31400259_31451966
8,f13a6c81-621e-4b63-bb14-1a6da0040d2a,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,sorry rumput tetangga lebih hijau,1,2,2.3.0_4786731_4861639,2025-04-06 09:59:11,NaN,NaN,2.3.0_4786731_4861639
9,b0bc28bb-6f07-45ec-a81c-3a20d406ac26,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,MANA TOMBOL SKIPNYA???,3,0,5.5.0_31400259_31451966,2025-04-06 09:27:57,NaN,NaN,5.5.0_31400259_31451966

| Kolom                | Deskripsi                                 |
|----------------------|--------------------------------------------|
| `reviewId`           | ID unik untuk review                       |
| `userName`           | Nama pengguna                              |
| `userImage`          | URL foto profil pengguna                   |
| `content`            | Isi review                                 |
| `score`              | Nilai rating (1–5)                         |
| `thumbsUpCount`      | Jumlah likes pada review                   |
| `reviewCreatedVersion` | Versi aplikasi saat review dibuat        |
| `at`                 | Tanggal review                             |
| `replyContent`       | Balasan dari developer (jika ada)          |
| `repliedAt`          | Tanggal balasan                            |
| `appVersion`         | Versi aplikasi                             |

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 216034 entries, 0 to 216033
Data columns (total 11 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   reviewId              216034 non-null  object
 1   userName              216034 non-null  object
 2   userImage             216034 non-null  object
 3   content               216034 non-null  object
 4   score                 216034 non-null  int64
 5   thumbsUpCount         216034 non-null  int64
 6   reviewCreatedVersion  139560 non-null  object
 7   at                    216034 non-null  object
 8   replyContent          14365 non-null   object
 9   repliedAt             14365 non-null   object
 10  appVersion            139560 non-null  object
dtypes: int64(2), object(9)
memory usage: 18.1+ MB

## 🗃️ Drop Kolom

In [32]:
df_cleaned = df.drop(
    columns=['userName', 'userImage', 'replyContent', 'repliedAt', 'reviewCreatedVersion'])

Kolom 'userName' dan 'userImage' di-drop karena tidak mengandung informasi tekstual yang relevan untuk analisis NLP — mereka hanya metadata pengguna.  
Kolom 'replyContent' dan 'repliedAt' juga tidak digunakan karena fokus analisis NLP berada pada konten utama, bukan pada balasan atau timestamp-nya.
Kolom 'ReviewCreatedVersion' juga di-drop karena informasinya redundan — nilainya sama dengan kolom 'appVersion'.

## 🔄 Ubah Tipe Data

In [33]:
df_cleaned['at'] = pd.to_datetime(df_cleaned['at'], errors='coerce')

In [34]:
df_cleaned.head()

,reviewId,content,score,thumbsUpCount,at,appVersion
0,044af800-8184-463d-915d-e9382c4cdde7,👌,5,0,2025-04-06 12:38:51,5.5.0_31400259_31451966
1,e8e32740-62b4-4755-ae8b-0d50c71d7e33,comeback menggunakan Infinix 50 hot pro plus d...,5,0,2025-04-06 12:29:10,1.5.0_2574575_2578841
2,39853dd9-f562-4b6b-8621-7fa14465cfd3,"Game baik wkwk tapi jujur aza dari segi lore, ...",5,0,2025-04-06 12:14:41,5.5.0_31400259_31451966
3,380ae1d4-16f2-4db2-83bd-f14ba776f76f,Testing di HP Helio g99 dan ternyata sangat la...,5,1,2025-04-06 11:48:46,5.5.0_31400259_31451966
4,3548cb24-2d7e-423f-98f3-f11586a27144,Benerin sistem preupdate di ps4 kacau banget!,5,2,2025-04-06 11:35:44,5.5.0_31400259_31451966

In [35]:
df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 216034 entries, 0 to 216033
Data columns (total 6 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   reviewId       216034 non-null  object
 1   content        216034 non-null  object
 2   score          216034 non-null  int64
 3   thumbsUpCount  216034 non-null  int64
 4   at             216034 non-null  datetime64[ns]
 5   appVersion     139560 non-null  object
dtypes: datetime64[ns](1), int64(2), object(3)
memory usage: 9.9+ MB